import { Injectable } from '@angular/core';
import {
  AttendanceRecord,
  Cleaner,
  CleaningTask,
  Location,
  Notification,
  Room,
  RoomAssignment,
  User,
} from '../models';

@Injectable({ providedIn: 'root' })
export class MockDataService {
  readonly users: User[] = [
    {
      id: 'u1',
      email: 'admin@cleanops.com',
      firstName: 'Alex',
      lastName: 'Morgan',
      role: 'admin',
      phone: '+1 555-0100',
      isActive: true,
      createdAt: '2024-01-15T08:00:00Z',
    },
    {
      id: 'u2',
      email: 'supervisor@cleanops.com',
      firstName: 'Sarah',
      lastName: 'Chen',
      role: 'supervisor',
      phone: '+1 555-0101',
      isActive: true,
      createdAt: '2024-02-01T08:00:00Z',
    },
    {
      id: 'u3',
      email: 'cleaner@cleanops.com',
      firstName: 'James',
      lastName: 'Wilson',
      role: 'cleaner',
      phone: '+1 555-0102',
      isActive: true,
      createdAt: '2024-03-10T08:00:00Z',
    },
    {
      id: 'u4',
      email: 'maria.garcia@cleanops.com',
      firstName: 'Maria',
      lastName: 'Garcia',
      role: 'cleaner',
      phone: '+1 555-0103',
      isActive: true,
      createdAt: '2024-04-05T08:00:00Z',
    },
    {
      id: 'u5',
      email: 'david.kim@cleanops.com',
      firstName: 'David',
      lastName: 'Kim',
      role: 'cleaner',
      phone: '+1 555-0104',
      isActive: true,
      createdAt: '2024-05-20T08:00:00Z',
    },
    {
      id: 'u6',
      email: 'lisa.park@cleanops.com',
      firstName: 'Lisa',
      lastName: 'Park',
      role: 'supervisor',
      phone: '+1 555-0105',
      isActive: true,
      createdAt: '2024-06-01T08:00:00Z',
    },
  ];

  readonly cleaners: Cleaner[] = [
    {
      ...this.users[2],
      employeeId: 'CLN-001',
      employmentStatus: 'active',
      hireDate: '2024-03-10',
      performanceScore: 92,
      supervisorId: 'u2',
    },
    {
      ...this.users[3],
      employeeId: 'CLN-002',
      employmentStatus: 'active',
      hireDate: '2024-04-05',
      performanceScore: 88,
      supervisorId: 'u2',
    },
    {
      ...this.users[4],
      employeeId: 'CLN-003',
      employmentStatus: 'active',
      hireDate: '2024-05-20',
      performanceScore: 76,
      supervisorId: 'u2',
    },
  ];

  readonly locations: Location[] = [
    { id: 'loc1', name: 'Main Building', type: 'building' },
    { id: 'loc2', name: 'Floor 1', type: 'floor', parentId: 'loc1' },
    { id: 'loc3', name: 'Floor 2', type: 'floor', parentId: 'loc1' },
    { id: 'loc4', name: 'East Wing', type: 'department', parentId: 'loc2' },
  ];

  readonly rooms: Room[] = [
    {
      id: 'r1',
      number: '101',
      name: 'Room 101',
      building: 'Main Building',
      floor: 'Floor 1',
      department: 'East Wing',
      status: 'clean',
      qrCode: 'QR-R101',
      locationId: 'loc4',
    },
    {
      id: 'r2',
      number: '102',
      name: 'Room 102',
      building: 'Main Building',
      floor: 'Floor 1',
      department: 'East Wing',
      status: 'dirty',
      qrCode: 'QR-R102',
      locationId: 'loc4',
      deadline: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'r3',
      number: '103',
      name: 'Room 103',
      building: 'Main Building',
      floor: 'Floor 1',
      status: 'in_progress',
      qrCode: 'QR-R103',
      locationId: 'loc2',
    },
    {
      id: 'r4',
      number: '201',
      name: 'Room 201',
      building: 'Main Building',
      floor: 'Floor 2',
      status: 'pending_verification',
      qrCode: 'QR-R201',
      locationId: 'loc3',
    },
    {
      id: 'r5',
      number: '202',
      name: 'Room 202',
      building: 'Main Building',
      floor: 'Floor 2',
      status: 'overdue',
      qrCode: 'QR-R202',
      locationId: 'loc3',
      deadline: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'r6',
      number: '203',
      name: 'Room 203',
      building: 'Main Building',
      floor: 'Floor 2',
      status: 'dirty',
      qrCode: 'QR-R203',
      locationId: 'loc3',
    },
  ];

  assignments: RoomAssignment[] = [
    {
      id: 'a1',
      roomId: 'r2',
      cleanerId: 'u3',
      assignedBy: 'u2',
      assignedAt: new Date().toISOString(),
      isActive: true,
    },
    {
      id: 'a2',
      roomId: 'r3',
      cleanerId: 'u3',
      assignedBy: 'u2',
      assignedAt: new Date().toISOString(),
      isActive: true,
    },
    {
      id: 'a3',
      roomId: 'r4',
      cleanerId: 'u4',
      assignedBy: 'u2',
      assignedAt: new Date().toISOString(),
      isActive: true,
    },
    {
      id: 'a4',
      roomId: 'r5',
      cleanerId: 'u5',
      assignedBy: 'u2',
      assignedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      isActive: true,
    },
    {
      id: 'a5',
      roomId: 'r6',
      cleanerId: 'u4',
      assignedBy: 'u2',
      assignedAt: new Date().toISOString(),
      isActive: true,
    },
  ];

  tasks: CleaningTask[] = [
    {
      id: 't1',
      roomId: 'r3',
      cleanerId: 'u3',
      assignmentId: 'a2',
      status: 'in_progress',
      startedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      beforePhotoUrl: 'https://picsum.photos/seed/before1/400/300',
      qrVerified: true,
      estimatedDurationMinutes: 45,
      gpsStart: { latitude: 40.7128, longitude: -74.006 },
    },
    {
      id: 't2',
      roomId: 'r4',
      cleanerId: 'u4',
      assignmentId: 'a3',
      status: 'pending_verification',
      startedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
      completedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      beforePhotoUrl: 'https://picsum.photos/seed/before2/400/300',
      afterPhotoUrl: 'https://picsum.photos/seed/after2/400/300',
      qrVerified: true,
      estimatedDurationMinutes: 45,
      gpsStart: { latitude: 40.7128, longitude: -74.006 },
      gpsComplete: { latitude: 40.7128, longitude: -74.006 },
    },
    {
      id: 't3',
      roomId: 'r5',
      cleanerId: 'u5',
      assignmentId: 'a4',
      status: 'assigned',
      qrVerified: false,
      estimatedDurationMinutes: 45,
    },
  ];

  attendance: AttendanceRecord[] = [
    {
      id: 'att1',
      cleanerId: 'u3',
      date: new Date().toISOString().split('T')[0],
      checkIn: new Date(new Date().setHours(8, 5)).toISOString(),
      status: 'present',
      gpsCheckIn: { latitude: 40.7128, longitude: -74.006 },
    },
    {
      id: 'att2',
      cleanerId: 'u4',
      date: new Date().toISOString().split('T')[0],
      checkIn: new Date(new Date().setHours(8, 25)).toISOString(),
      status: 'late',
      gpsCheckIn: { latitude: 40.7128, longitude: -74.006 },
    },
    {
      id: 'att3',
      cleanerId: 'u5',
      date: new Date().toISOString().split('T')[0],
      status: 'absent',
    },
  ];

  notifications: Notification[] = [
    {
      id: 'n1',
      userId: 'u2',
      title: 'Task Completed',
      message: 'Maria Garcia completed Room 201 cleaning.',
      type: 'success',
      read: false,
      createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    {
      id: 'n2',
      userId: 'u2',
      title: 'Cleaner Checked In',
      message: 'James Wilson checked in at 8:05 AM.',
      type: 'info',
      read: false,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'n3',
      userId: 'u2',
      title: 'Overdue Room',
      message: 'Room 202 is past its cleaning deadline.',
      type: 'warning',
      read: true,
      createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    },
  ];
}
